version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DIRECTUS_URL: ${DIRECTUS_URL}
        DIRECTUS_URL: ${DIRECTUS_URL}
        DIRECTUS_TOKEN: ${DIRECTUS_TOKEN}
        NEXT_PUBLIC_ASSETS_URL: ${NEXT_PUBLIC_ASSETS_URL}
        MONO_TOKEN: ${MONO_TOKEN}
        DIRECTUS_BASE_URL: ${DIRECTUS_BASE_URL}
        NOVA_POSHTA_API_KEY: ${NOVA_POSHTA_API_KEY}
        RESEND_API_KEY: ${RESEND_API_KEY}
        CLIENT_ORDER_URL_BASE: ${CLIENT_ORDER_URL_BASE}
    environment:
        NEXT_PUBLIC_DIRECTUS_URL: ${DIRECTUS_URL}
        DIRECTUS_URL: ${DIRECTUS_URL}
        DIRECTUS_TOKEN: ${DIRECTUS_TOKEN}
        NEXT_PUBLIC_ASSETS_URL: ${NEXT_PUBLIC_ASSETS_URL}
        MONO_TOKEN: ${MONO_TOKEN}
        DIRECTUS_BASE_URL: ${DIRECTUS_BASE_URL}
        NOVA_POSHTA_API_KEY: ${NOVA_POSHTA_API_KEY}
        RESEND_API_KEY: ${RESEND_API_KEY}
        CLIENT_ORDER_URL_BASE: ${CLIENT_ORDER_URL_BASE}
        PORT: ${CONTAINER_PORT}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    restart: unless-stopped
