name: Next.js Docker Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  CONTAINER_PORT: 3000
  HOST_PORT: 8080

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ‚¨áÔ∏è Checkout code
        uses: actions/checkout@v4

      - name: üÜî Convert repository name to lowercase
        id: repo_lc
        run: echo "value=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: üõ†Ô∏è Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: üîê Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: üèóÔ∏è Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.repo_lc.outputs.value }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: üì§ Deploy to VPS and Run Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            APP_NAME="next-shop-app"
            IMAGE_URL="${{ env.REGISTRY }}/${{ steps.repo_lc.outputs.value }}:latest"

            echo "--- –ó–∞–ø—É—Å–∫ –¥–µ–ø–ª–æ—é –Ω–∞ VPS ---"
            
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ${{ env.REGISTRY }} -u "${{ github.actor }}" --password-stdin
            
            echo "–ó–∞–≤–∞–Ω—Ç–∞–∂–µ–Ω–Ω—è –æ–±—Ä–∞–∑—É: $IMAGE_URL"
            docker pull $IMAGE_URL

            if docker ps -a | grep -q $APP_NAME; then
                docker stop $APP_NAME
                docker rm $APP_NAME
            fi
            
            docker run -d \
                --name $APP_NAME \
                -p ${{ env.HOST_PORT }}:${{ env.CONTAINER_PORT }} \
                --restart unless-stopped \
                $IMAGE_URL
                
            docker system prune -f
            
            echo "--- –î–µ–ø–ª–æ–π —É—Å–ø—ñ—à–Ω–æ –∑–∞–≤–µ—Ä—à–µ–Ω–æ! ---"
